server:
  port: 7779
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  data:
    mongodb:
      user: mongo
      password: password
      uri: mongodb://localhost:27017/public