version: "3"

services:
  postgres:
    image: postgres
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
    #   timeout: 45s
    #   interval: 10s
    #   retries: 10
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      # - APP_DB_USER=docker
      # - APP_DB_PASS=docker
      # - APP_DB_NAME=docker
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    ports:
      - 15432:5432
    networks:
      - postgres
networks:
  postgres:
    name: postgres
