version: "3"

services:
  mongo:
    image: mongo
    container_name: "ecn-tp-database-mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=public
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:z
      # - ./config/mongod.conf:/etc/mongod.conf:z
      # - ./db/mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
    networks:
      - mongo
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: ecn-tp-database-mongo
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - mongo
networks:
  mongo:
    name: mongo
