version: "3"

services:
  postgres:
    image: postgres
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
    #   timeout: 45s
    #   interval: 10s
    #   retries: 10
    # restart: always
    container_name: "ecn-tp-database-sql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      # - APP_DB_USER=docker
      # - APP_DB_PASS=docker
      # - APP_DB_NAME=docker
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d:z
    ports:
      - 5432:5432
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
      PGPASSFILE: /pgadmin4/pgpass.conf
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json:z
      - ./config/pgpass.conf:/pgadmin4/pgpass.conf:z
    ports:
      - 15432:80
    depends_on:
      - postgres
    networks:
      - postgres
networks:
  postgres:
    name: postgres
